### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by juliohm** [jwscook/NelderMead.jl#5]
It would be nice if you could register this package. Currently it is not possible to add it as a dependency.

**Comment by jwscook** [comment]
Sure - I'll register it since it's getting wider usage. Might have to wait until the weekend.

In the meantime, you should be able to add it to the Project.toml via `]add https://github.com/jwscook/NelderMead.jl.git`

**Comment by jwscook** [comment]
@JuliaRegistrator register()

**Comment by jwscook** [comment]
The package has been registered :)
