### ISSUE TITLE
Help porting from Optim.jl to NelderMead.jl

### ISSUE THREAD

**Issue by juliohm** [jwscook/NelderMead.jl#7]
@jwscook we are trying to migrate from Optim.jl to NelderMead.jl because it is a lighter dependency that does what we need. Can you help refactoring these two lines of code?

https://github.com/JuliaML/TableTransforms.jl/blob/222d30bcb805c20c1cf1be94e46467deb7fc8255/src/transforms/projectionpursuit.jl#L114-L115

**Comment by jwscook** [comment]
I'm in the process of doing this, but wanted to remove some unwanted surprises first, see #8.

**Comment by jwscook** [comment]
@JuliaRegistrator register()
